
@startuml
skinparam nodesep 60
skinparam ranksep 80
top to bottom direction

package "User Module" {
    entity User {
        id: bigint <<PK>>
        roleId: bigint <<FK>>
        status: int
        createdAt: Timestamp
        createdUser: bigint
        updatedAt: Timestamp
        updatedUser: bigint
        parentId: bigint
        name:string
        userName: string
        dob: date
        phone: string
        email: string
        password: encoded string
    }

    entity Role{
        id: bigint <<PK>>
        name: string
    }
    entity Module{
        id: bigint <<PK>>
        name: string
        path: string
    }
    entity Action{
        id: bigint <<PK>>
        name: string
        path: string
    }
    entity Permission{
        id: bigint <<PK>>
        moduleId: bigint <<FK>>
        actionId: bigint <<FK>>
        name: string
    }
    entity RolePermission{
        id: bigint <<PK>>
        roleId: bigint <<FK>>
        permissionId: bigint <<FK>>
    }
}

package "Story Module" {
    entity StoryBank{
        id: bigint <<PK>>
        status: int
        createdAt: Timestamp
        createdUser: bigint
        updatedAt: Timestamp
        updatedUser: bigint
        approvedBy: bigint <<FK>>
        approvedAt: Timestamp 
        rejectedReason: string
        publishedAt: Timestamp
        version: int
        ageGroup: string
        duration: int
        topicId: bigint <<FK>>
        isPremium: boolean 
        imageUrl: string
        audioUrl: string
        name: string
        description: string
        view: bigint
    }
    
    entity StoryScene{
        id: bigint <<PK>>
        status: int
        createdAt: Timestamp
        createdUser: bigint
        updatedAt: Timestamp
        updatedUser: bigint
        storyBankId: bigint <<FK>>
        name:string
        description:string
    }
    
    entity StoryFeedback{
        id: bigint <<PK>>
        status: int
        createdAt: Timestamp
        createdUser: bigint
        updatedAt: Timestamp
        updatedUser: bigint
        storyBankId: bigint <<FK>>
        rate: bigint
        content: string
    }
    entity GraphicAsset{
        id: bigint <<PK>>
        status: int
        createdAt: Timestamp
        createdUser: bigint
        updatedAt: Timestamp
        updatedUser: bigint
        storyBankId: bigint <<FK>>
        storySceneId: bigint <<FK>>
        name:string
        description: string
        imageUrl: string
        type: GraphicType
    }
    entity AudioAsset{
        id: bigint <<PK>>
        status: int
        createdAt: Timestamp
        createdUser: bigint
        updatedAt: Timestamp
        updatedUser: bigint
        storyBankId: bigint <<FK>>
        storySceneId: bigint <<FK>>
        name:string
        description: string
        audioUrl: string
        type: AudioType
    }
    
}

package "Assignment Module" {
     entity Assignment{
        id: bigint <<PK>>
        status: int
        createdAt: Timestamp
        createdUser: bigint
        updatedAt: Timestamp
        updatedUser: bigint
        topicId: bigint <<FK>>
        name: string
        description: string
        total: bigint
        isShuffle: boolean
    
    }

    entity QuestionBank{
        id: bigint <<PK>>
        status: int
        createdAt: Timestamp
        createdUser: bigint
        updatedAt: Timestamp
        updatedUser: bigint
        assignmentId: bigint <<FK>>
        questionList: jsonb
    }

    entity Topic{
        id: bigint <<PK>>
        status: int
        createdAt: Timestamp
        createdUser: bigint
        updatedAt: Timestamp
        updatedUser: bigint
        name:string
        description: string
    }
}

package "Logs & Payments Module" {
    entity ChildrenStoryLog{
        id: bigint <<PK>>
        status: int
        userId: bigint <<FK>>
        storyBankId: bigint <<FK>>
        content: jsonb
        createdAt: Timestamp
        updatedAt: Timestamp
        completedAt: Timestamp  
    }

    entity AssignmentLog{
        id: bigint <<PK>>
        status: int
        createdAt: Timestamp
        createdUser: bigint
        updatedAt: Timestamp
        updatedUser: bigint
        assignmentId: bigint <<FK>>
        userId : bigint <<FK>>
        questionList: jsonb
        finishedAt: Timestamp
        version: int
    }

    entity PreorderStory{
        id: bigint <<PK>>
        status: int
        userId: bigint <<FK>>
        storyBankId: bigint <<FK>>
        orderDate: date
    }

    entity BlackListStory{
        id: bigint <<PK>>
        status: int
        userId: bigint <<FK>>
        storyBankId: bigint <<FK>>
    }

    entity TimeLimit{
        id: bigint <<PK>>
        status: int
        createdAt: Timestamp
        createdUser: bigint
        updatedAt: Timestamp
        updatedUser: bigint
        userId: bigint<<FK>>
        limitDate: date
        limitTime: double
    }

    entity ParentPayment{
        id: bigint <<PK>>
        status: int
        createdAt: Timestamp
        createdUser: bigint
        updatedAt: Timestamp
        updatedUser: bigint
        userId: bigint <<FK>>
        total: bigint
        paymentTypeId: bigint <<FK>>
    }

    entity PaymentType{
        id: bigint <<PK>>
        name: string 
    }

    entity PaymentDescription{
        id: bigint <<PK>>
        status: int
        createdAt: Timestamp
        createdUser: bigint
        updatedAt: Timestamp
        updatedUser: bigint
        parentPaymentId: bigint <<FK>>
        startDate: Timestamp
        endDate: Timestamp
    }
}

package "Game Module" {
    entity GameBank{
        id: bigint <<PK>>
        status: int
        createdAt: Timestamp
        createdUser: bigint
        updatedAt: Timestamp
        updatedUser: bigint
        gameTypeId: bigint <<FK>>
        imageUrl: string
        name: string
        description: string
        view: bigint
        ageGroup: string
        topicId: bigint <<FK>>
        isPremium: boolean
    }

    entity GameType{
        id: bigint <<PK>>
        status: int
        createdAt: Timestamp
        createdUser: bigint
        updatedAt: Timestamp
        updatedUser: bigint
        name: string
    }

    entity GameLog {
    id: bigint <<PK>>
    status: int
    createdAt: Timestamp
    userId: bigint <<FK>>
    gameBankId: bigint <<FK>>
    score: int
    finishedAt: Timestamp
}
}

package "Notification Module" {
    entity Notification {
        id: bigint <<PK>>
        status: int
        createdAt: Timestamp
        createdUser: bigint
        updatedAt: Timestamp
        updatedUser: bigint
        title: string
        content: string
        type: NotificationType
        isGlobal: boolean
    }

    entity NotificationTarget {
        id: bigint <<PK>>
        notificationId: bigint <<FK>>
        userId: bigint <<FK>>
    }

    entity NotificationLog {
        id: bigint <<PK>>
        notificationId: bigint <<FK>>
        userId: bigint <<FK>>
        isRead: boolean
        readAt: Timestamp
    }
}


' package "Enum"{
'     enum UserStatus{
'         0: ACTIVE
'         1: INACTIVE
'         2: BANNED
'     }
'     enum StoryStatus{
'        0:PENDING
'         1:CERTIFIED
'         2:UNCERTIFIED
'     }
'     enum StoryLogStatus{
'         0: INPROGRESS
'         1: COMPLETED
'     }
'     enum PaymentStatus{
'         0: PENDING
'         1: COMPLETED
'     }
'     enum GraphicType{
'         Character
'         Background
'         Animation
'     }
'     enum AudioType{
'         VOICEOVER
'         SOUNDEFFECT
'         MUSIC
'     }
' }

User }o--o| User : parent of

StoryBank ||-down-o{ StoryScene : has
StoryScene }--o{ GraphicAsset : has
StoryScene }--o{ AudioAsset : has
StoryBank ||--o{ StoryFeedback : has

Assignment }o-left-|| Topic
Assignment ||-right-|| QuestionBank

StoryBank ||-down-o{ ChildrenStoryLog
StoryBank ||-down-o{ PreorderStory
StoryBank ||-down-o{ GraphicAsset
StoryBank ||-down-o{ AudioAsset


Assignment ||-down-o{ AssignmentLog

ParentPayment ||-right-o{ PaymentDescription : has
ParentPayment }o--|| User
ParentPayment }o--|| PaymentType

User ||--|| Role
User ||--o{ BlackListStory
User ||--o{ TimeLimit
User ||--o{ StoryBank : approves
User ||--o{ StoryBank : creates
User ||--o{ AssignmentLog
User ||--o{ PreorderStory
User ||--o{ ChildrenStoryLog
User ||--o{ StoryFeedback

Notification ||--o{ NotificationTarget : targets
Notification ||--o{ NotificationLog : logs
NotificationTarget }o--|| User
NotificationLog }o--|| User

Permission }o--|| Module
Permission }o--|| Action

RolePermission }o--|| Role
RolePermission }o--|| Permission

GameBank }o--|| GameType


@enduml

